### ISSUE TITLE
unable to build variable fonts for SansDevanagari*, SansGujarati*, SansMyanmar*

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#256]
I'm unable to build the following variable fonts:

NotoSansDevanagari
NotoSansDevanagariUI
NotoSansGujarati
NotoSansGujaratiUI
NotoSansMyanmar
NotoSansMyanmarUI

**Comment by marekjez86** [comment]
fontmake: Error: In 'src/NotoSansDevanagari/NotoSansDevanagari-MM.glyphs' -> 'master_ufo/NotoSansDevanagari.designspace': Generating fonts from Designspace failed: ((81, (80, 81, 86, 84, 80, 81, 86, 84)), 'int', '[6]', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', '[0]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GSUB', '.table', 'table_G_S_U_B_')

fontmake: Error: In 'src/NotoSansDevanagari/NotoSansDevanagari-MM.glyphs' -> 'master_ufo/NotoSansDevanagariUI.designspace': Generating fonts from Designspace failed: ((81, (80, 81, 86, 84, 80, 81, 86, 84)), 'int', '[6]', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', '[0]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GSUB', '.table', 'table_G_S_U_B_')

fontmake: Error: In 'src/NotoSansGujarati/NotoSansGujarati-MM.glyphs' -> 'master_ufo/NotoSansGujarati.designspace': Generating fonts from Designspace failed: ((74, (74, 74, 72, 72, 74, 74, 72)), 'int', '[4]', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', '[11]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GSUB', '.table', 'table_G_S_U_B_')

fontmake: Error: In 'src/NotoSansMyanmar/NotoSansMyanmar-MM.glyphs' -> 'master_ufo/NotoSansMyanmar.designspace': Generating fonts from Designspace failed: ((20, [20, 20, 20, 20, 21, 21, 21, 21]), 'list', '.ChainSubClassRule', 'ChainSubClassSet', '[1]', 'list', '.ChainSubClassSet', 'ChainContextSubst', '[0]', 'Lookup', '[50]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GSUB', '.table', 'table_G_S_U_B_')

fontmake: Error: In 'src/NotoSansMyanmarUI/NotoSansMyanmarUI-MM.glyphs' -> 'master_ufo/NotoSansMyanmarUI.designspace': Generating fonts from Designspace failed: ((20, [20, 20, 20, 20, 21, 21, 21, 21]), 'list', '.ChainSubClassRule', 'ChainSubClassSet', '[1]', 'list', '.ChainSubClassSet', 'ChainContextSubst', '[0]', 'Lookup', '[50]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GSUB', '.table', 'table_G_S_U_B_')

**Comment by nizarsq** [comment]
I can't reproduce this issue. Tried to build variable fonts for NotoSansGujarati-MM. glyphs, NotoSansMyanmar-MM.glyphs and NotoSansMyanmarUI-MM. glyphs, all was ok.

**Comment by marekjez86** [comment]
@nizarsq : for these fonts one needs to use the following:
./build src/NotoSansDevanagari/NotoSansDevanagari-MM.plist
./build src/NotoSansGujarati/NotoSansGujarati-MM.plist
./build src/NotoSansMyanmar/NotoSansMyanmar-MM.plist
./build src/NotoSansMyanmarUI/NotoSansMyanmarUI.plist

is this what you used?

**Comment by nizarsq** [comment]
I didn't use plist. I think that's the reason why I'm not getting the errors you mentioned. 
I'm working one another font right now. I'll wrap up and see if I can find the reason for the errors you mentioned (I noticed something with those fonts but let me check first and see if that's the reason for the errors).

**Comment by nizarsq** [comment]
@marekjez86 not sure if what I'm going to say makes any sense, but here what I'm suspecting is the issue; I'm seeing some kind of inconstancy between the list of masters in Plist and  Designspace files (in terms of masters). NotoSansGujarati.Plist not listing Thin as a master and .glyphs don't have Thin master), but Designspace is listing Thin weight and it seems throw an error because it expecting it to be there. I THINK that could be the reason but since I didn't do any actual tracing it will be just a possible reason.

**Comment by punchcutter** [comment]
This is the same issue that it has always been for years and going back to the fact that these were originally not expected to be variable fonts because there was no such thing when the project started. So the way the sources with plist are compiled requires that all GSUB and GPOS lookups match (at least the number of lookups) across masters. In these files they don't match so there's no way to build a variable font. In these examples it's the GSUB lookups that differ across masters. I'd have to look more closely to see how easy it is to update to get them in sync.

**Comment by simoncozens** [comment]
When converting these to Glyphs/FEA sources, I also made the layout interpolatable. All should be buildable as variable fonts now.
